name: spotify-analysis
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pandas
  - numpy
  - dash
  - plotly
  - pip
  - pip:
    - plotly-calplot
    - requests
    - tekore